# Default values for panosc-portal-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



panoscPortal:
  namespace: panosc-portal

cloudProviderKubernetes:
  instancesNamespace: panosc-kubernetes-instances
  nodePort: 32300

panoscPortalPostgres:
  host: panosc-portal-postgres
  username: cloud-provider-kubernetes
  password: panosc
  port: 5432
  type: postgres
  databaseName: cloud-provider-kubernetes
  schema: cloud-provider-kubernetes
  nodePort: 32301
