apiVersion: v1
kind: Deployment
metadata:
  name: panosc-portal-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: panosc-portal-postgres
    spec:
      hostname: panosc-portal-postgres
      containers:
        - name: panosc-portal-postgres
          image: panosc-portal-postgres
          imagePullPolicy: "Never"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: panosc-postgres-config
