apiVersion: apps/v1
kind: Deployment
metadata:
  name: panosc-portal-postgres
  namespace: panosc-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panosc-portal-postgres
  template:
    metadata:
      labels:
        app: panosc-portal-postgres
    spec:
      containers:
        - name: panosc-portal-postgres
          image: panosc-portal-postgres
          imagePullPolicy: "Never"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: panosc-portal-postgres-config
