{{- if and .Values.dockerRegistry.host .Values.dockerRegistry.username .Values.dockerRegistry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerRegistry.host | replace "." "-" }}
  namespace: {{ .Values.panoscPortal.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
