apiVersion: v1
kind: Service
metadata:
  name: panosc-portal-postgres
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: panosc-portal-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: {{ .Values.panoscPortalPostgres.nodePort }}
  selector:
   app: panosc-portal-postgres
