apiVersion: apps/v1
kind: Deployment
metadata:
  name: panosc-portal-postgres
  namespace: {{ .Values.panoscPortal.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panosc-portal-postgres
  template:
    metadata:
      labels:
        app: panosc-portal-postgres
    spec:
      containers:
        - name: panosc-portal-postgres
          image: postgres:9.6
          ports:
              - containerPort: 5432
          env:
            - name: CLOUD_PROVIDER_K8S_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: panosc-portal-postgres-secret
                  key: CLOUD_PROVIDER_K8S_DATABASE_PASSWORD
          envFrom:
            - configMapRef:
                name: panosc-portal-postgres-config
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-file
            - mountPath: /tmp/
              name: sql-dump
      {{- if and .Values.dockerRegistry.host .Values.dockerRegistry.username .Values.dockerRegistry.password }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistry.host | replace "." "-" }}
      {{ end }}
      volumes:
        - name: init-file
          configMap:
            name: panosc-portal-postgres-shconfig
        - name: sql-dump
          configMap:
            name: panosc-portal-postgres-sqldump
