apiVersion: v1
kind: Secret
metadata:
  name: panosc-portal-postgres-secret
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: panosc-portal-postgres
data:
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.panoscPortalPostgres.password | b64enc | quote}}
