apiVersion: v1
kind: ConfigMap
metadata:
  name: panosc-portal-postgres-config
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: panosc-portal-postgres
data:
  POSTGRES_HOST_AUTH_METHOD: "trust"