apiVersion: v1
kind: ConfigMap
metadata:
  name: panosc-portal-postgres-sqldump
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: panosc-portal-postgres
data:
{{(.Files.Glob "postgres-config-files/*.sql").AsConfig | indent 4 }}

