apiVersion: apps/v1
kind: Deployment
metadata:
  name: panosc-portal-postgres
  namespace: {{ .Values.panoscPortal.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panosc-portal-postgres
  template:
    metadata:
      labels:
        app: panosc-portal-postgres
    spec:
      containers:
        - name: panosc-portal-postgres
          image: {{ .Values.dockerRegistry.url }}:{{ .Values.dockerRegistry.port }}/panosc-portal/postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: panosc-portal-postgres-config
      {{- if and .Values.dockerRegistry.host .Values.dockerRegistry.username .Values.dockerRegistry.password }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistry.host | replace "." "-" }}
      {{ end }}
