apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-kubernetes-config
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: cloud-provider-kubernetes
data:
  CLOUD_PROVIDER_K8S_DATABASE_HOST: {{ .Values.panoscPortalPostgres.host | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_USERNAME: {{ .Values.panoscPortalPostgres.username | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.panoscPortalPostgres.password | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_PORT: {{ .Values.panoscPortalPostgres.port | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_TYPE: {{ .Values.panoscPortalPostgres.type | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_NAME: {{ .Values.panoscPortalPostgres.databaseName | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_SCHEMA: {{ .Values.panoscPortalPostgres.schema | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_LOGGING: "false"
  CLOUD_PROVIDER_K8S_DATABASE_SYNCHRONIZE: "false"
  CLOUD_PROVIDER_K8S_LOG_LEVEL: "debug"
