apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: cloud-provider-kubernetes-rolebinding
roleRef:
 kind: ClusterRole
 name: cloud-provider-kubernetes-cluster-role
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: cloud-provider-kubernetes-sa
   namespace: {{ .Values.panoscPortal.namespace }}