apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-provider-kubernetes-cluster-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods", "services", "namespaces", "deployments", "secrets","nodes"]
    verbs: ["list", "get","create", "delete"]
