apiVersion: v1
kind: Service
metadata:
  name: cloud-provider-kubernetes
  namespace: {{ .Values.panoscPortal.namespace }}
spec:
  type: NodePort
  selector:
    app: cloud-provider-kubernetes
  ports:
    - port: 3000
      nodePort: {{ .Values.cloudProviderKubernetes.nodePort }}
